// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace User_Management.Models;

[PrimaryKey("UserId", "BillId")]
[Table("billcustomer")]
[Index("BillId", Name = "bill_bill_customer_idx")]
public partial class Billcustomer
{
    [Key]
    [Column("userId")]
    [MaxLength(16)]
    public byte[] UserId { get; set; }

    [Key]
    [Column("billId")]
    public int BillId { get; set; }

    [Column("status")]
    public sbyte? Status { get; set; }

    [ForeignKey("BillId")]
    [InverseProperty("Billcustomer")]
    public virtual Bill Bill { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Billcustomer")]
    public virtual User User { get; set; }
}