// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace User_Management.Models;

[Table("bill")]
public partial class Bill
{
    [Key]
    [Column("billId")]
    public int BillId { get; set; }

    [Column("amount")]
    public int? Amount { get; set; }

    [InverseProperty("Bill")]
    public virtual ICollection<Billcustomer> Billcustomer { get; set; } = new List<Billcustomer>();

    [ForeignKey("BillId")]
    [InverseProperty("Bill")]
    public virtual ICollection<Telcoservices> Service { get; set; } = new List<Telcoservices>();
}