// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace User_Management.Models;

[Table("telcoservices")]
public partial class Telcoservices
{
    [Key]
    [Column("serviceId")]
    public int ServiceId { get; set; }

    [Required]
    [Column("serviceName")]
    [StringLength(45)]
    public string ServiceName { get; set; }

    [Column("monthlyCharge")]
    public int? MonthlyCharge { get; set; }

    [ForeignKey("ServiceId")]
    [InverseProperty("Service")]
    public virtual ICollection<Bill> Bill { get; set; } = new List<Bill>();

    [ForeignKey("ServiceId")]
    [InverseProperty("Service")]
    public virtual ICollection<User> User { get; set; } = new List<User>();
}