// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace User_Management.Models;

[Table("user")]
[Index("PhoneNumber", Name = "phoneNumber_UNIQUE", IsUnique = true)]
public partial class User
{
    [Key]
    [Column("userId")]
    [MaxLength(16)]
    public byte[] UserId { get; set; }

    [Column("name")]
    [StringLength(45)]
    public string Name { get; set; }

    [Column("userName")]
    [StringLength(45)]
    public string UserName { get; set; }

    [Column("phoneNumber")]
    [StringLength(45)]
    public string PhoneNumber { get; set; }

    [InverseProperty("User")]
    public virtual Auth Auth { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Billcustomer> Billcustomer { get; set; } = new List<Billcustomer>();

    [ForeignKey("UserId")]
    [InverseProperty("User")]
    public virtual ICollection<Telcoservices> Service { get; set; } = new List<Telcoservices>();
}