// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using User_Management.Models;

namespace User_Management.DataModels;

[Serializable]
public partial class UserData
{
    public string UserName { get; set; }

    public string Password { get; set; }
}